// One-off generator: extracts the v15 DDL from the released app_db.dart
// (git HEAD) into a Dart test fixture.
//
// Only two regions are read on purpose:
//   1. the onCreate body  - the 10 tables a fresh v15 install gets
//   2. the _createSyncSchema helper - sync_queue + trip_instances
// The onUpgrade body is deliberately skipped: those CREATE TABLE statements
// are the legacy drop-and-recreate paths for pre-v14 devices and would
// corrupt a v15 fixture.
const fs = require('fs');
const src = fs.readFileSync(process.argv[2], 'utf8');

function region(from, to) {
  const a = src.indexOf(from);
  if (a < 0) throw new Error('not found: ' + from);
  const b = to ? src.indexOf(to, a) : src.length;
  return src.slice(a, b < 0 ? src.length : b);
}

function ddlIn(body) {
  const stmts = [];
  let i = 0;
  while (true) {
    const at = body.indexOf('d.execute(', i);
    if (at < 0) break;
    let j = at + 'd.execute('.length;
    while (/\s/.test(body[j])) j++;
    const q = body.slice(j, j + 3) === "'''" ? "'''" : body[j];
    const open = q === "'''" ? j + 3 : j + 1;
    const closeIdx = body.indexOf(q, open);
    if (closeIdx < 0) throw new Error('unterminated literal near offset ' + at);
    let sql = body.slice(open, closeIdx);
    i = closeIdx + q.length;
    if (q === "'") sql = sql.replace(/''/g, "'");
    if (q === '"') sql = sql.replace(/\\"/g, '"');
    sql = sql.trim().replace(/;+\s*$/, '');
    if (!/^CREATE\s+(UNIQUE\s+)?(TABLE|INDEX)/i.test(sql)) continue;
    if (/\bTEMP\b|\bVIEW\b|\bTRIGGER\b/i.test(sql)) continue;
    stmts.push(sql);
  }
  return stmts;
}

const seen = new Set();
const stmts = [];
for (const sql of [
  ...ddlIn(region('onCreate: (d, v) async {', 'onUpgrade:')),
  ...ddlIn(region('static Future<void> _createSyncSchema', 'static Future<void> _seedFares')),
]) {
  const key = sql.replace(/\s+/g, ' ').toLowerCase();
  if (seen.has(key)) continue;
  seen.add(key);
  stmts.push(sql);
}

const out = `// GENERATED by tool/gen_v15_fixture.js from the released (v15) app_db.dart.
// DO NOT EDIT BY HAND - this is the exact on-disk schema of a field device
// running app 1.0.0+20, used to exercise the real v15 -> v16 migration.
const List<String> v15SchemaSql = <String>[
${stmts.map((s) => "  r'''" + s + "''',").join('\n')}
];
`;
fs.mkdirSync('test/fixtures', { recursive: true });
fs.writeFileSync(process.argv[3], out);
console.log('extracted ' + stmts.length + ' DDL statements');
