import jsPDF from 'jspdf';
import { getCompanyBrand, money } from './companyBrand';

const BRAND = {
  navy: [45, 27, 105] as [number, number, number],
  purple: [168, 85, 247] as [number, number, number],
  red: [185, 28, 28] as [number, number, number],
  cyan: [0, 229, 255] as [number, number, number],
  green: [33, 115, 70] as [number, number, number],
  gold: [255, 215, 0] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  lightGray: [243, 232, 255] as [number, number, number],
  darkText: [30, 30, 30] as [number, number, number],
  mutedText: [120, 120, 120] as [number, number, number],
  maroon: [33, 18, 78] as [number, number, number],
};

type BrandInfo = { name: string; support_phone: string; website: string; email: string; address: string };

function drawHeader(doc: jsPDF, title: string, from: string, to: string, w: number, brand: BrandInfo, cont = false) {
  // Deep purple top bar
  doc.setFillColor(...BRAND.navy);
  doc.rect(0, 0, w, 38, 'F');
  // Neon purple accent stripe
  doc.setFillColor(...BRAND.purple);
  doc.rect(0, 38, w, 3, 'F');
  // Brand name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...BRAND.white);
  doc.text(brand.name.toUpperCase(), 14, 22);
  // Title
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.cyan);
  doc.text(cont ? `${title} (cont.)` : title, 14, 32);
  // Date range right-aligned
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text(`${from}  to  ${to}`, w - 14, 22, { align: 'right' });
  doc.text(new Date().toLocaleDateString('en-GB'), w - 14, 30, { align: 'right' });
}

function drawFooter(doc: jsPDF, w: number, h: number, brand: BrandInfo) {
  // Deep purple bottom bar
  doc.setFillColor(...BRAND.maroon);
  doc.rect(0, h - 16, w, 16, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(200, 200, 200);
  const left = [brand.name, brand.support_phone || brand.email].filter(Boolean).join(' | ');
  doc.text(left, 14, h - 7);
  doc.text(`Generated by Preyone POS System · ${new Date().toLocaleDateString('en-GB')}`, w - 14, h - 7, {
    align: 'right',
  });
}

function drawStatCard(doc: jsPDF, x: number, y: number, cw: number, ch: number, label: string, value: string, hint: string) {
  doc.setFillColor(...BRAND.lightGray);
  doc.roundedRect(x, y, cw, ch, 3, 3, 'F');
  doc.setDrawColor(200, 200, 200);
  doc.roundedRect(x, y, cw, ch, 3, 3, 'S');
  // Label
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.purple);
  doc.text(label.toUpperCase(), x + 6, y + 10);
  // Value
  doc.setFontSize(14);
  doc.setTextColor(...BRAND.darkText);
  doc.text(value, x + 6, y + 21);
  // Hint
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(...BRAND.mutedText);
  doc.text(hint, x + 6, y + 27);
}

function drawTable(doc: jsPDF, x: number, startY: number, w: number, cols: { label: string; key: string; align?: string }[], rows: Record<string, any>[], maxRows = 12) {
  let y = startY;
  const rowH = 9;
  const colWidths = cols.map(() => w / cols.length);
  // Header
  doc.setFillColor(...BRAND.navy);
  doc.rect(x, y, w, rowH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.white);
  cols.forEach((c, i) => {
    const cx = x + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
    doc.text(c.label, cx + 4, y + 6);
  });
  y += rowH;
  // Rows
  const slice = rows.slice(0, maxRows);
  slice.forEach((r, ri) => {
    if (ri % 2 === 0) {
      doc.setFillColor(...BRAND.lightGray);
      doc.rect(x, y, w, rowH, 'F');
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.darkText);
    cols.forEach((c, ci) => {
      const cx = x + colWidths.slice(0, ci).reduce((a, b) => a + b, 0);
      const val = String(r[c.key] ?? '—');
      doc.text(val, cx + 4, y + 6);
    });
    y += rowH;
  });
  return y;
}

function drawBarChart(doc: jsPDF, x: number, y: number, w: number, h: number, data: { label: string; value: number }[]) {
  if (data.length === 0) return;
  // Background
  doc.setFillColor(248, 248, 248);
  doc.roundedRect(x, y, w, h, 3, 3, 'F');
  const maxVal = Math.max(...data.map(d => d.value), 1);
  const barGap = 3;
  const barW = Math.min((w - 10) / data.length - barGap, 18);
  const chartH = h - 18;
  const startX = x + 5;
  data.forEach((d, i) => {
    const bh = Math.max((d.value / maxVal) * (chartH - 4), 2);
    const bx = startX + i * (barW + barGap);
    const by = y + chartH - bh + 2;
    // Gradient-like bar: neon purple to cyan
    const ratio = i / Math.max(data.length - 1, 1);
    const r = Math.round(168 * (1 - ratio) + 0 * ratio);
    const g = Math.round(85 * (1 - ratio) + 229 * ratio);
    const b = Math.round(247 * (1 - ratio) + 255 * ratio);
    doc.setFillColor(r, g, b);
    doc.roundedRect(bx, by, barW, bh, 1, 1, 'F');
    // Label
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(5);
    doc.setTextColor(...BRAND.mutedText);
    doc.text(d.label, bx + barW / 2, y + chartH + 8, { align: 'center' });
  });
  // Y-axis line
  doc.setDrawColor(200, 200, 200);
  doc.line(x + 4, y + 2, x + 4, y + chartH + 2);
}

export async function exportReportPdf(data: any, from: string, to: string, presetLabel?: string) {
  const brand = await getCompanyBrand();
  const cur = brand.currency;
  const $ = (n: number) => money(n, cur);
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const t = data.totals;
  const margin = 14;
  const contentW = w - margin * 2;
  const title = presetLabel ? `${presetLabel} Sales Report` : 'Sales Report';

  // Page 1: Header + KPI + Bar Chart
  drawHeader(doc, title, from, to, w, brand);

  let y = 48;

  // KPI Cards (4 across)
  const cardW = (contentW - 9) / 4;
  const cardH = 30;
  const cards = [
    { label: 'Revenue', value: $(Number(t?.revenue || 0)), hint: `${t?.docs || 0} documents` },
    {
      label: 'Collected',
      value: $(Number(t?.collected || 0)),
      hint: `Balance ${$(Number(t?.revenue || 0) - Number(t?.collected || 0))}`,
    },
    {
      label: 'Profit',
      value: $(Number(t?.profit || 0)),
      hint: Number(t?.revenue) > 0 ? `${((Number(t?.profit) / Number(t?.revenue)) * 100).toFixed(1)}% margin` : '0% margin',
    },
    { label: 'VAT / Tax', value: $(Number(t?.vat || 0)), hint: 'Taxable sales' },
  ];
  cards.forEach((c, i) => {
    drawStatCard(doc, margin + i * (cardW + 3), y, cardW, cardH, c.label, c.value, c.hint);
  });
  y += cardH + 10;

  // Bar chart (daily revenue)
  if (data.byDay?.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.darkText);
    doc.text('Daily Revenue', margin, y);
    y += 4;
    const chartH = 45;
    const chartData = data.byDay.slice(-14).map((d: any) => ({
      label: new Date(d.day).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' }),
      value: Number(d.revenue) || 0,
    }));
    drawBarChart(doc, margin, y, contentW, chartH, chartData);
    y += chartH + 14;
  }

  // Page break check
  if (y > h - 80) {
    drawFooter(doc, w, h, brand);
    doc.addPage();
    drawHeader(doc, title, from, to, w, brand, true);
    y = 48;
  }

  // Payment Method table
  if (data.byMethod?.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.darkText);
    doc.text('By Payment Method', margin, y);
    y += 4;
    const cols = [
      { label: 'METHOD', key: 'method' },
      { label: 'COUNT', key: 'count' },
      { label: 'TOTAL', key: 'total' },
    ];
    const rows = data.byMethod.map((r: any) => ({
      method: r.method?.charAt(0).toUpperCase() + r.method?.slice(1),
      count: String(r.count),
      total: $(Number(r.total)),
    }));
    y = drawTable(doc, margin, y, contentW, cols, rows);
    y += 8;
  }

  // Best Sellers table
  if (data.bestSellers?.length) {
    if (y > h - 60) {
      drawFooter(doc, w, h, brand);
      doc.addPage();
      drawHeader(doc, title, from, to, w, brand, true);
      y = 48;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.darkText);
    doc.text('Best Sellers', margin, y);
    y += 4;
    const cols = [
      { label: 'ITEM', key: 'description' },
      { label: 'QTY', key: 'qty_sold' },
      { label: 'REVENUE', key: 'revenue' },
      { label: 'PROFIT', key: 'profit' },
    ];
    const rows = data.bestSellers.map((r: any) => ({
      description: r.description,
      qty_sold: String(r.qty_sold),
      revenue: $(Number(r.revenue)),
      profit: $(Number(r.profit)),
    }));
    y = drawTable(doc, margin, y, contentW, cols, rows);
    y += 8;
  }

  // Staff Performance table
  if (data.byCashier?.length) {
    if (y > h - 60) {
      drawFooter(doc, w, h, brand);
      doc.addPage();
      drawHeader(doc, title, from, to, w, brand, true);
      y = 48;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.darkText);
    doc.text('Staff Performance', margin, y);
    y += 4;
    const cols = [
      { label: 'CASHIER', key: 'cashier' },
      { label: 'DOCS', key: 'docs' },
      { label: 'REVENUE', key: 'revenue' },
      { label: 'COLLECTED', key: 'collected' },
    ];
    const rows = data.byCashier.map((r: any) => ({
      cashier: r.cashier,
      docs: String(r.docs),
      revenue: $(Number(r.revenue)),
      collected: $(Number(r.collected)),
    }));
    y = drawTable(doc, margin, y, contentW, cols, rows);
    y += 8;
  }

  // Low Stock Alerts
  if (data.lowStock?.length) {
    if (y > h - 50) {
      drawFooter(doc, w, h, brand);
      doc.addPage();
      drawHeader(doc, title, from, to, w, brand, true);
      y = 48;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.darkText);
    doc.text('Low Stock Alerts', margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    data.lowStock.forEach((p: any) => {
      doc.setFillColor(255, 240, 220);
      doc.roundedRect(margin, y, contentW, 8, 2, 2, 'F');
      doc.setTextColor(200, 100, 0);
      doc.text(`${p.name} — ${Number(p.stock_qty)} left`, margin + 4, y + 5.5);
      y += 10;
    });
  }

  drawFooter(doc, w, h, brand);

  const brandName = brand.name.replace(/[^A-Za-z0-9 _-]/g, '').replace(/\s+/g, '_') || 'Preyone';
  doc.save(`${brandName}-POS-Report-${from}-to-${to}.pdf`);
}