type LogoPictureProps = {
  src: string
  alt: string
  className?: string
  width?: number
  height?: number
  eager?: boolean
}

/**
 * Renders a <picture> block that serves AVIF, then WebP, then the original
 * PNG fallback — plus width/height so no layout shift occurs. The optimized
 * variants are generated by `npm run optimize` (scripts/optimize-images.mjs).
 */
export function LogoPicture({ src, alt, className, width, height, eager }: LogoPictureProps) {
  const isPng = src.endsWith('.png')
  const base = src.replace(/\.(png|webp|avif)$/, '')
  return (
    <picture>
      {isPng && (
        <>
          <source srcSet={`${base}.avif`} type="image/avif" />
          <source srcSet={`${base}.webp`} type="image/webp" />
        </>
      )}
      <img
        src={src}
        alt={alt}
        className={className}
        width={width}
        height={height}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
      />
    </picture>
  )
}